title: GM valcke's dungeon
description: A place where I keep my creations locked up. Though some might be up for adoption to a good home.

baseurl: "" # e.g. "/my-repo" for project sites
url: "https://GM-Valcke.github.io" # replace USERNAME

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

exclude: []
